feat: first try correction github actions determine aws account id

diff --git a/.github/workflows/aws_cd.yml b/.github/workflows/aws_cd.yml
--- a/.github/workflows/aws_cd.yml
+++ b/.github/workflows/aws_cd.yml
@@ -14,6 +14,18 @@ jobs:
       contents: read
     steps:
         - uses: actions/checkout@v2
+        - name: Determine AWS account ID
+          run: |
+            if [[ "${{ github.ref_name }}" == "dev" ]]; then
+              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV
+            elif [[ "${{ github.ref_name }}" == "homolog" ]]; then
+              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_HOML }}" >> $GITHUB_ENV
+            elif [[ "${{ github.ref_name }}" == "prod" ]]; then
+              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_PROD }}" >> $GITHUB_ENV
+            else
+              echo "Invalid branch name!" && exit 1
+            fi
+
         - name: Setup AWS Credentials
           uses: aws-actions/configure-aws-credentials@v2
           with:
