feat: fix workflow of the action

diff --git a/.github/workflows/aws_cd.yml b/.github/workflows/aws_cd.yml
--- a/.github/workflows/aws_cd.yml
+++ b/.github/workflows/aws_cd.yml
@@ -13,119 +13,80 @@ jobs:
       id-token: write
       contents: read
     steps:
-        - uses: actions/checkout@v2
-        - name: Determine AWS account ID
-          run: |
-            if [[ "${{ github.ref_name }}" == "dev" ]]; then
-              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV
-            elif [[ "${{ github.ref_name }}" == "homolog" ]]; then
-              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_HOML }}" >> $GITHUB_ENV
-            elif [[ "${{ github.ref_name }}" == "prod" ]]; then
-              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_PROD }}" >> $GITHUB_ENV
-            else
-              echo "Invalid branch name!" && exit 1
-            fi
+      - uses: actions/checkout@v2
+      
+      # 1. Configuração inicial
+      - name: Determine AWS account ID
+        run: |
+          if [[ "${{ github.ref_name }}" == "dev" ]]; then
+            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV
+          elif [[ "${{ github.ref_name }}" == "homolog" ]]; then
+            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_HOMOLOG }}" >> $GITHUB_ENV
+          elif [[ "${{ github.ref_name }}" == "prod" ]]; then
+            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_PROD }}" >> $GITHUB_ENV
+          else
+            echo "Invalid branch name!" && exit 1
+          fi
+          echo "AWS_REGION=sa-east-1" >> $GITHUB_ENV
 
-        - name: Verify AWS Account ID
-          run: |
-            if [ -z "${{ env.AWS_ACCOUNT_ID }}" ]; then
-              echo "::error::AWS_ACCOUNT_ID is not set!"
-              exit 1
-            fi
+      # 2. Instalação de dependências
+      - name: Use Node.js 18.x
+        uses: actions/setup-node@v3
+        with:
+          node-version: 18.x
+      
+      - name: Install AWS CDK
+        run: npm install -g aws-cdk
 
-        - name: Setup AWS Credentials
-          uses: aws-actions/configure-aws-credentials@v2
-          with:
-            aws-region: sa-east-1
-            role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionsRole
-            role-session-name: github-action
-        - name: Use Node.js 18.x
-          uses: actions/setup-node@v3
-          with:
-            node-version: 18.x
-        - name: Setting stage and stack name
-          run: |
-            echo "STAGE=${{ github.ref_name }}" 
-            PROJECT_NAME=$(echo ${{ github.event.repository.name }} | sed -e 's/[-_]/ /g' | awk '{for(i=1;i<=NF;i++)sub(/./,toupper(substr($i,1,1)),$i)}1' | sed -e 's/ //g')
-            if [ "${#PROJECT_NAME}" -gt 64 ]; then
-              echo "Error: PROJECT_NAME is too long. It should be less than or equal to 64 characters."
-              exit 1
-            fi
-            echo "PROJECT_NAME=${PROJECT_NAME}"
-            echo "STACK_NAME=${PROJECT_NAME}StackFront${{github.ref_name}}"
+      # 3. Configuração AWS
+      - name: Setup AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-region: sa-east-1
+          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionsRole
+          role-session-name: github-action
 
-            echo "STACK_NAME=${PROJECT_NAME}StackFront${{github.ref_name}}" >> $GITHUB_ENV
-            echo "PROJECT_NAME=${PROJECT_NAME}Front" >> $GITHUB_ENV
-        - name: Installing Dependencies
-          run: |
-            cd iac
-            npm install
-            npm install -g aws-cdk
+      # 4. Bootstrap (agora com região definida)
+      - name: Bootstrap CDK
+        run: |
+          cd iac
+          npm install
+          cdk bootstrap aws://${{ env.AWS_ACCOUNT_ID }}/${{ env.AWS_REGION }}
 
-        - name: Bootstrap Check
-          run: |
-            cd iac
-            cdk bootstrap aws://${{ env.AWS_ACCOUNT_ID }}/${{ vars.AWS_REGION }} 
+      # 5. Build e Deploy
+      - name: Build and Export
+        run: |
+          npm install
+          npm run build
 
-        - name: DeployWithCDK
-          run: |
-              cd iac
-              cdk synth
-              cdk deploy --require-approval never
-          env:
-              AWS_REGION: ${{ vars.AWS_REGION }}
-              AWS_ACCOUNT_ID: ${{ env.AWS_ACCOUNT_ID }}
-              STACK_NAME: ${{ env.STACK_NAME }}
-              GITHUB_REF_NAME: ${{ github.ref_name }}
-              MSS_NAME: ${{ github.event.repository.name }}
-              PROJECT_NAME: ${{ github.event.repository.name }}
-              S3_ASSETS_CDN: ${{ vars.S3_ASSETS_CDN }}
-              AUTH_DEV_SYSTEM_USERPOOL_ARN_DEV: ${{ secrets.AUTH_DEV_SYSTEM_USERPOOL_ARN_DEV }}
-              AUTH_DEV_SYSTEM_USERPOOL_ARN_PROD: ${{ secrets.AUTH_DEV_SYSTEM_USERPOOL_ARN_PROD }}
-              REPLY_TO_EMAIL: ${{ vars.REPLY_TO_EMAIL }}
-              FROM_EMAIL: ${{ vars.FROM_EMAIL }}
-              HIDDEN_COPY: ${{ vars.HIDDEN_COPY }}
-              S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
-        - name: Build and Export
-          run: |
-            npm install
-            npm run build
-        - name: Setup envs
-          run: |
-            echo AWS_REGION=sa-east-1 >> $GITHUB_ENV
-            echo AWS_ACCOUNT_ID=${{ env.AWS_ACCOUNT_ID }} >> $GITHUB_ENV
-            echo STACK_NAME=${{ env.STACK_NAME }} >> $GITHUB_ENV
-            echo GITHUB_REF_NAME=${{ github.ref_name }} >> $GITHUB_ENV
-            echo ACM_CERTIFICATE_ARN=${{ secrets.DEVMAUA_ACM_CERTIFICATE_ARN }} >> $GITHUB_ENV
-            echo HOSTED_ZONE_ID=${{ secrets.DEVMAUA_HOSTED_ZONE_ID }} >> $GITHUB_ENV
-            if [ -z "${{ vars.ALTERNATIVE_DOMAIN_NAME }}" ]; then
-              echo ALTERNATIVE_DOMAIN_NAME=$(echo ${{ env.PROJECT_NAME }} | tr '[:upper:]' '[:lower:]').devmaua.com >> $GITHUB_ENV
-            else
-              echo ALTERNATIVE_DOMAIN_NAME=${{ vars.ALTERNATIVE_DOMAIN_NAME }} >> $GITHUB_ENV
-            fi
-            
-            echo ${{ env.AWS_REGION }}
-            echo ${{ env.AWS_ACCOUNT_ID }}
-            echo ${{ env.STACK_NAME }}
-            echo ${{ env.GITHUB_REF_NAME }}
-            echo ${{ env.ACM_CERTIFICATE_ARN }}
-            echo ${{ env.HOSTED_ZONE_ID }}
-            echo ${{ env.ALTERNATIVE_DOMAIN_NAME }}
+      - name: Verify Bootstrap
+        run: |
+          cd iac
+          aws ssm get-parameter --name /cdk-bootstrap/hnb659fds/version --region ${{ env.AWS_REGION }} || cdk bootstrap aws://${{ env.AWS_ACCOUNT_ID }}/${{ env.AWS_REGION }}
 
-        - name: Deploy with CDK
-          run: |
-            cd iac
-            cdk synth
-            cdk deploy --require-approval never 
-        - name: Set CloudFront ID
-          run: |
-            CLOUD_FRONT_ID=$(aws cloudformation --region ${{env.AWS_REGION}} describe-stacks --stack-name ${{env.STACK_NAME}} --query "Stacks[0].Outputs[?OutputKey=='${{env.PROJECT_NAME}}DistributionId${{github.ref_name}}'].OutputValue" --output text)
-            echo "CLOUD_FRONT_ID='$CLOUD_FRONT_ID'" >> $GITHUB_ENV
-        - name: Set AWS Bucket
-          run: |
-            AWS_BUCKET=$(aws cloudformation --region ${{env.AWS_REGION}} describe-stacks --stack-name ${{env.STACK_NAME}} --query "Stacks[0].Outputs[?OutputKey=='${{env.PROJECT_NAME}}BucketName${{github.ref_name}}'].OutputValue" --output text)
-            echo "AWS_BUCKET='$AWS_BUCKET'" >> $GITHUB_ENV
-        - name: Upload to S3
-          run: aws s3 cp dist s3://${{env.AWS_BUCKET}}/ --recursive --region sa-east-1
-        - name: Clear CDN cache
-          run: aws cloudfront create-invalidation --distribution-id ${{env.CLOUD_FRONT_ID}} --paths "/*" --region us-east-1
+      - name: Deploy with CDK
+        run: |
+          cd iac
+          cdk synth
+          cdk deploy --require-approval never
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
+          AWS_REGION: sa-east-1
+          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_DEV }}
+          AWS_DEFAULT_REGION: sa-east-1
+          AWS_DEFAULT_OUTPUT: json
+
+      - name: Set CloudFront ID
+        run: |
+          CLOUD_FRONT_ID=$(aws cloudformation --region ${{env.AWS_REGION}} describe-stacks --stack-name ${{env.STACK_NAME}} --query "Stacks[0].Outputs[?OutputKey=='${{env.PROJECT_NAME}}DistributionId${{github.ref_name}}'].OutputValue" --output text)
+          echo "CLOUD_FRONT_ID='$CLOUD_FRONT_ID'" >> $GITHUB_ENV
+      - name: Set AWS Bucket
+        run: |
+          AWS_BUCKET=$(aws cloudformation --region ${{env.AWS_REGION}} describe-stacks --stack-name ${{env.STACK_NAME}} --query "Stacks[0].Outputs[?OutputKey=='${{env.PROJECT_NAME}}BucketName${{github.ref_name}}'].OutputValue" --output text)
+          echo "AWS_BUCKET='$AWS_BUCKET'" >> $GITHUB_ENV
+      - name: Upload to S3
+        run: aws s3 cp dist s3://${{env.AWS_BUCKET}}/ --recursive --region sa-east-1
+      - name: Clear CDN cache
+        run: aws cloudfront create-invalidation --distribution-id ${{env.CLOUD_FRONT_ID}} --paths "/*" --region us-east-1
